# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'ec2-aws'
    runOptions: 'inline'
    inline: |
      cd db1-projects/health-panel-backend/;
      docker container stop HealthPanel;
      docker rm HealthPanel;
      git pull origin main
      docker rmi health-panel;
      docker build -t health-panel .;
      docker run -d -t -i -e ASPNETCORE_ENVIRONMENT=Production -p 5000:5000 --name HealthPanel health-panel;
    interactiveSession: true
    readyTimeout: '20000'



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
