version: '3.3'

services:  
    mysqldev:
        image: mysql:8.2.0
        environment:
          MYSQL_ROOT_PASSWORD: 123mudar
          MYSQL_DATABASE: mysql
          MYSQL_USER: keycloak
          MYSQL_PASSWORD: 123mudar
        ports:
          - 3306:3306
        restart: always
    keycloak:
        image: quay.io/keycloak/keycloak:23.0.3
        environment:
          KC_HOSTNAME: localhost
          KC_HOSTNAME_PORT: 7080
          KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
          KC_DB: mysql
          KC_DB_URL: jdbc:mysql://mysqldev:3306/meu_schema?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
          KC_DB_USERNAME: root
          KC_DB_PASSWORD: 123mudar
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: "true"
          KC_LOG_LEVEL: info
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
          interval: 15s
          timeout: 2s
          retries: 15
        command:
          [ "start-dev", "--import-realm" ]
        volumes:
          - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
        ports:
          - 7080:8080
          - 7443:7443
        depends_on:
          - mysqldev